/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ementor;

import javax.swing.JOptionPane;

/**
 *
 * @author LAZARO
 */
public class Cadastros extends javax.swing.JFrame {

    /** Creates new form Cadastros */
    public Cadastros() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seletor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TDataNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TPeriodo = new javax.swing.JTextField();
        TDataAdmissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TSalarioBruto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Seletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Opção", "Aluno", "Professor" }));
        Seletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeletorActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome*");

        TNome.setPreferredSize(new java.awt.Dimension(8, 21));

        jLabel2.setText("CPF*");

        jLabel3.setText("Data Nascimento");

        jLabel4.setText("Contato");

        jLabel5.setText("Matrícula*");

        jLabel6.setText("Data Admissão*");

        jLabel7.setText("Período*");

        jLabel8.setText("Salário Bruto*");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Lázaro José Pedrosa dos Reis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(Seletor, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TDataNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TSalarioBruto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(TCPF)
                            .addComponent(jLabel4)
                            .addComponent(TTelefone)
                            .addComponent(TDataAdmissao)
                            .addComponent(TPeriodo)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Seletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SeletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeletorActionPerformed
        //Seletor de aluno ou professor
        
        if (Seletor.getSelectedIndex()==0){ //Opcao default, desaparece com as opcoes de aluno e professor
            jLabel5.setVisible(false);
            TMatricula.setVisible(false);            
            jLabel7.setVisible(false);
            TPeriodo.setVisible(false);
            jLabel6.setVisible(false);
            TDataAdmissao.setVisible(false);            
            jLabel8.setVisible(false);
            TSalarioBruto.setVisible(false);
        }
        else if (Seletor.getSelectedIndex()==1){
            jLabel5.setVisible(true);
            TMatricula.setVisible(true);            
            jLabel7.setVisible(true);
            TPeriodo.setVisible(true);
            
            jLabel6.setVisible(false);
            TDataAdmissao.setVisible(false);            
            jLabel8.setVisible(false);
            TSalarioBruto.setVisible(false);
        }
        else if (Seletor.getSelectedIndex()==2){
            jLabel5.setVisible(false);
            TMatricula.setVisible(false);            
            jLabel7.setVisible(false);
            TPeriodo.setVisible(false);
            
            jLabel6.setVisible(true);
            TDataAdmissao.setVisible(true);            
            jLabel8.setVisible(true);
            TSalarioBruto.setVisible(true);
        }
    }//GEN-LAST:event_SeletorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Arquivos arq = new Arquivos();
        
        if (Seletor.getSelectedIndex()==0)
            JOptionPane.showMessageDialog(null,"Selecione uma Opção Válida!","Informação",JOptionPane.INFORMATION_MESSAGE);
        
        if (Seletor.getSelectedIndex()==1){//Aluno
            
            if (TNome.getText().isEmpty()||TCPF.getText().isEmpty()
                    ||TMatricula.getText().isEmpty()||TPeriodo.getText().isEmpty())                
              JOptionPane.showMessageDialog(null,"Preencha os campos Obrigatórios *","Informação",JOptionPane.WARNING_MESSAGE);
            
            else{
            Aluno [] Academico = new Aluno [100];//Cria vetor para carregar os dados do formulário e posteriormente gravar em disco
            
            /*Seção de verificar existencia de arquivos físicos - executa somente uma vez */
            if (arq.lerDoDiscoIndiceI("indiceAluno.txt")==0){
               arq.salvarNoDiscoIndiceI(0, "indiceAluno.txt");
               arq.salvarNoDisco(Academico, "aluno.txt");
              }
            /*Seção para recuperar no arquivo físico o último índice e também as informações salvas via vetor */
            int i = arq.lerDoDiscoIndiceI("indiceAluno.txt");
            Academico = (Aluno []) arq.lerDoDisco(Academico, "aluno.txt");
            
            /*Seção de copiar os dados dos campos do formulário para um objeto da classe Aluno */
            Aluno ObjetoAluno = new Aluno ();
            //setDados( String nome, String data, long cpf, String contato, long Matricula, int Periodo) {
            ObjetoAluno.setDados(TNome.getText(), TDataNascimento.getText(), 
                                 Long.parseLong(TCPF.getText()), 
                                 TTelefone.getText(),
                                 Long.parseLong(TMatricula.getText()),
                                 Integer.parseInt(TPeriodo.getText()));
            /*Seção para gravar os dados contidos no objeto, em uma posição do vetor, para o arquivo físico*/
            Academico[i] = ObjetoAluno;
            i=i+1; //proxima posição livre do vetor Academico a ser gravada para nova recuperação
            ObjetoAluno.imprimeDados();
            arq.salvarNoDiscoIndiceI(i, "indiceAluno.txt");//grava índice
            arq.salvarNoDisco(Academico, "aluno.txt");//grava dados contidos no vetor de objetos
            /*Seção para limpar os campos do formulário  */
            TNome.setText("");
            TCPF.setText("");
            TDataNascimento.setText("");
            TTelefone.setText("");
            TMatricula.setText("");
            TPeriodo.setText("");
            JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!","Salvar",JOptionPane.PLAIN_MESSAGE);
            }
         }
        
        else if (Seletor.getSelectedIndex()==2){//Professor
            if (TNome.getText().isEmpty()||TCPF.getText().isEmpty()
                    ||TSalarioBruto.getText().isEmpty() || TDataAdmissao.getText().isEmpty())                
              JOptionPane.showMessageDialog(null,"Preencha os campos Obrigatórios *","Informação",JOptionPane.WARNING_MESSAGE);
        
            else{
                Professor [] Academico = new Professor [100];//Cria vetor para carregar os dados do formulário e posteriormente gravar em disco

                /*Seção de verificar existencia de arquivos físicos - executa somente uma vez */
                if (arq.lerDoDiscoIndiceI("indiceProfessor.txt")==0){
                   arq.salvarNoDiscoIndiceI(0, "indiceProfessor.txt");
                   arq.salvarNoDisco(Academico, "professor.txt");
                  }
                /*Seção para recuperar no arquivo físico o último índice e também as informações salvas via vetor */
                int i = arq.lerDoDiscoIndiceI("indiceProfessor.txt");
                Academico = (Professor []) arq.lerDoDisco(Academico, "professor.txt");

                /*Seção de copiar os dados dos campos do formulário para um objeto da classe Aluno */
                Professor ObjetoProfessor = new Professor ();
                
                //setDados( String nome, String data, long cpf, String contato, long Matricula, int Periodo) {
                ObjetoProfessor.SetDados(TDataAdmissao.getText(),Double.parseDouble(TSalarioBruto.getText()),TNome.getText(),TDataNascimento.getText(),Long.parseLong(TCPF.getText()),TTelefone.getText());
                
                /*Seção para gravar os dados contidos no objeto, em uma posição do vetor, para o arquivo físico*/
                Academico[i] = ObjetoProfessor;
                i=i+1; //proxima posição livre do vetor Academico a ser gravada para nova recuperação
                ObjetoProfessor.imprimeDados();
                arq.salvarNoDiscoIndiceI(i, "indiceProfessor.txt");//grava índice
                arq.salvarNoDisco(Academico, "professor.txt");//grava dados contidos no vetor de objetos
                /*Seção para limpar os campos do formulário  */
                TNome.setText("");
                TCPF.setText("");
                TDataNascimento.setText("");
                TTelefone.setText("");
                TDataAdmissao.setText("");
                TSalarioBruto.setText("");

                JOptionPane.showMessageDialog(null,"Cadastro realizado com sucesso!","Salvar",JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            ListaAcademicosProfessores Lista = new ListaAcademicosProfessores();
            Lista.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    if (Seletor.getSelectedIndex()==0){
            jLabel5.setVisible(false);
            TMatricula.setVisible(false);            
            jLabel7.setVisible(false);
            TPeriodo.setVisible(false);
            jLabel6.setVisible(false);
            TDataAdmissao.setVisible(false);            
            jLabel8.setVisible(false);
            TSalarioBruto.setVisible(false);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Seletor;
    private javax.swing.JTextField TCPF;
    private javax.swing.JTextField TDataAdmissao;
    private javax.swing.JTextField TDataNascimento;
    private javax.swing.JTextField TMatricula;
    private javax.swing.JTextField TNome;
    private javax.swing.JTextField TPeriodo;
    private javax.swing.JTextField TSalarioBruto;
    private javax.swing.JTextField TTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
